steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        cd anvil-rstudio-bioconductor
        tag=$(cat ./VERSION)
        docker build -t us.gcr.io/anvil-gcr-public/anvil-rstudio-bioconductor:$tag .
        docker push us.gcr.io/anvil-gcr-public/anvil-rstudio-bioconductor:$tag
timeout: 1200s