steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        cd anvil-rstudio-bioconductor
        tag=$(cat ./VERSION)
        docker pull ghcr.io/almahmoud/anvil-rstudio-bioconductor:3.17.0
        docker tag ghcr.io/almahmoud/anvil-rstudio-bioconductor:3.17.0 us.gcr.io/landmarkanvil/anvil-rstudio-bioconductor:ghcr
        docker push us.gcr.io/landmarkanvil/anvil-rstudio-bioconductor:ghcr
timeout: 3600s
