steps:
  - name: 'docker.io/docker:23.0'
    entrypoint: sh
    args:
      - -c
      - |
        cd anvil-rstudio-bioconductor
        tag=$(cat ./VERSION)
        DOCKER_BUILDKIT=1 docker buildx build -t us.gcr.io/landmarkanvil/anvil-rstudio-bioconductor:$tag .
        docker push us.gcr.io/landmarkanvil/anvil-rstudio-bioconductor:$tag
timeout: 3600s
