steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        cd anvil-rstudio-bioconductor-devel
        tag=$(cat ./VERSION)
        docker build -t us.gcr.io/anvil-gcr-public/anvil-rstudio-bioconductor-devel:$tag .
        docker push us.gcr.io/anvil-gcr-public/anvil-rstudio-bioconductor-devel:$tag